spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;trustServerCertificate=true
    username: sa
    password: VeRys3cr3t
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver